### PR TITLE
issue=#462 bugfix.sdk-python.types-and-destroy

### PR DESCRIPTION
**Pull request by taocp**
Python SDK

修复几个类型声明不匹配的问题和资源泄露问题。

### CODE REVIEW

**Comment by taocp** [comment]
build

**Comment by lylei** [comment]
build

**Comment by lylei** [comment]
build

**Comment by 00k** [comment]
build

**Comment by 00k** [comment]
build

**Comment by taocp** [comment]
build

**Comment by taocp** [comment]
关闭重提以分配reviewer.

**Pull request closed without merging**
