### PR TITLE
update build.sh

### PR DESCRIPTION
**Pull request by 00k**
1. move url and version config of deps from build.sh to build.conf
2. internal_build.sh invoke build.sh

### CODE REVIEW

**Comment by 00k** [comment]
build

**Comment by yvxiang** [comment]
link for zookeeper is unavailable?

**Comment by 00k** [comment]
the link is available but very slow in china

**Comment by xupeilin** [comment]
travic error

--2016-11-17 06:49:57--  http://www.us.apache.org/dist/zookeeper/stable/zookeeper-3.4.7.tar.gz
Resolving www.us.apache.org (www.us.apache.org)... 140.211.11.105
Connecting to www.us.apache.org (www.us.apache.org)|140.211.11.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-17 06:49:57 ERROR 404: Not Found.
The command "wget http://www.us.apache.org/dist/zookeeper/stable/zookeeper-3.4.7.tar.gz" failed and exited with 8 during .

**Comment by 00k** [comment]
travis关闭很久了，这个pr目的就是修好travis并重新启用，这个merge之后会搞个pr让travis直接调build.sh，这样以后更新依赖的时候travis也跟着更新了

**Pull request merged**
