### PR TITLE
issue=954 bugfix: one tablet may stay in OnMerge forever

### PR DESCRIPTION
**Pull request by 00k**
#954  
#1079

### CODE REVIEW

**Comment by 00k** [comment]
build

**Comment by caijieming-baidu** [comment]
has no test!

**Comment by xupeilin** [comment]
逻辑没有看出问题，还干掉了一个回调

**Comment by 00k** [comment]
@caijieming-baidu  add a new test case, please review

**Comment by caijieming-baidu** [comment]
LGTM

**Pull request merged**
